modLoader="javafml"
loaderVersion="[40,)"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    #logoFile="examplemod.png"
    #credits=""
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "dragonsurvival"
    mandatory = true
    versionRange = "[1.20.1-01.01.2024,]"
    ordering = "BEFORE"

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.1.67,)"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
